[pytest]
DJANGO_SETTINGS_MODULE = django_realtime_notifications.settings
python_files = tests.py test_*.py *_tests.py
addopts = --strict-markers --cov=notifications --cov-report=term-missing
asyncio_default_fixture_loop_scope = function
